name: Deploy web app
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CRED }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_CRED.subscriptionId }}
        resourceGroupName: rg-calicot-web-dev-19
        template: CalicotEncheres/web.bicep
        parameters: CalicotEncheres/bicep_params_web.json
        failOnStdErr: false
